Feat add validation funding dates
Health-Education-England/TIS-TCS pull request #1004
Opened 2024-07-09 10:19 UTC by jayanta2018

Given a user has the correct permissions
When they add or update a post funding record on the front end
Then Funding.StartDate must not be NULL

Given a user has the correct permissions
When they add or update a post funding record on the front end
Then if Funding.EndDate is not null then Funding.EndDate must not equal or be before Funding.StartDate

TIS21-5892

2024-07-09 13:23 UTC, JosephKelly requested changes
The Acceptance Criteria referenced on this PR are `add or update` but the update `PUT` endpoint hasn't been tested.  There are also some `PATCH` endpoint which is not clearly for the UI or bulk upload.

2024-07-10 11:01 UTC, jayanta2018 commented on tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/PostValidator.java
> +        }
Good spot. I have added a Null check for start date in the condition like this `&& postFundingDto.getStartDate() != null `

2024-07-10 11:07 UTC, jayanta2018 commented on tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/PostResourceIntTest.java
> +    invalidFunding.setStartDate(null);
Removed

2024-07-10 11:17 UTC, jayanta2018 commented on tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/PostResourceIntTest.java
> +    PostFundingDTO invalidFunding = new PostFundingDTO();
My bad. Changed to `validFunding1` and `validFunding2`

2024-07-10 11:51 UTC, jayanta2018 commented
> The Acceptance Criteria referenced on this PR are `add or update` but the update `PUT` endpoint hasn't been tested. There are also some `PATCH` endpoint which is not clearly for the UI or bulk upload.

Added one test case for `PUT`

2024-07-10 12:51 UTC, JosephKelly commented on tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/PostValidator.java
> +        }
It would be better to try and simplify the method.

2024-07-11 08:48 UTC, jayanta2018 commented on tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/PostValidator.java
> +        }
I have done it

2024-08-01 10:15 UTC, JosephKelly approved these changes

2024-08-01 10:29 UTC, merged